/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ImmigrationLinksRouteImport } from './routes/immigration-links'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AboutUsIndexRouteImport } from './routes/about-us.index'
import { Route as AboutUsCommunityInvolvementRouteImport } from './routes/about-us.community-involvement'
import { Route as AboutUsWhyAkulaRouteImport } from './routes/about-us.why-akula'
import { Route as ImmigrationServicesIndexRouteImport } from './routes/immigration-services.index'
import { Route as NewsBlogsIndexRouteImport } from './routes/news-blogs.index'
import { Route as NewsBlogsSlugRouteImport } from './routes/news-blogs.$slug'
import { Route as OurTeamIndexRouteImport } from './routes/our-team.index'
import { Route as OurTeamSlugRouteImport } from './routes/our-team.$slug'
import { Route as OurTeamFullTeamRouteImport } from './routes/our-team.full-team'
import { Route as VideoArchiveIndexRouteImport } from './routes/video-archive.index'
import { Route as VideoArchiveFirmVideosRouteImport } from './routes/video-archive.firm-videos'
import { Route as ImmigrationServicesCategoryIndexRouteImport } from './routes/immigration-services.$category.index'
import { Route as ImmigrationServicesCategorySlugRouteImport } from './routes/immigration-services.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrationLinksRoute = ImmigrationLinksRouteImport.update({
  id: '/immigration-links',
  path: '/immigration-links',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsCommunityInvolvementRoute =
  AboutUsCommunityInvolvementRouteImport.update({
    id: '/about-us/community-involvement',
    path: '/about-us/community-involvement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutUsWhyAkulaRoute = AboutUsWhyAkulaRouteImport.update({
  id: '/about-us/why-akula',
  path: '/about-us/why-akula',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrationServicesIndexRoute =
  ImmigrationServicesIndexRouteImport.update({
    id: '/immigration-services/',
    path: '/immigration-services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsBlogsIndexRoute = NewsBlogsIndexRouteImport.update({
  id: '/news-blogs/',
  path: '/news-blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsBlogsSlugRoute = NewsBlogsSlugRouteImport.update({
  id: '/news-blogs/$slug',
  path: '/news-blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamIndexRoute = OurTeamIndexRouteImport.update({
  id: '/our-team/',
  path: '/our-team/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamSlugRoute = OurTeamSlugRouteImport.update({
  id: '/our-team/$slug',
  path: '/our-team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamFullTeamRoute = OurTeamFullTeamRouteImport.update({
  id: '/our-team/full-team',
  path: '/our-team/full-team',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoArchiveIndexRoute = VideoArchiveIndexRouteImport.update({
  id: '/video-archive/',
  path: '/video-archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoArchiveFirmVideosRoute = VideoArchiveFirmVideosRouteImport.update({
  id: '/video-archive/firm-videos',
  path: '/video-archive/firm-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrationServicesCategoryIndexRoute =
  ImmigrationServicesCategoryIndexRouteImport.update({
    id: '/immigration-services/$category/',
    path: '/immigration-services/$category/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImmigrationServicesCategorySlugRoute =
  ImmigrationServicesCategorySlugRouteImport.update({
    id: '/immigration-services/$category/$slug',
    path: '/immigration-services/$category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/immigration-links': typeof ImmigrationLinksRoute
  '/testimonials': typeof TestimonialsRoute
  '/about-us/community-involvement': typeof AboutUsCommunityInvolvementRoute
  '/about-us/why-akula': typeof AboutUsWhyAkulaRoute
  '/news-blogs/$slug': typeof NewsBlogsSlugRoute
  '/our-team/$slug': typeof OurTeamSlugRoute
  '/our-team/full-team': typeof OurTeamFullTeamRoute
  '/video-archive/firm-videos': typeof VideoArchiveFirmVideosRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/immigration-services/': typeof ImmigrationServicesIndexRoute
  '/news-blogs/': typeof NewsBlogsIndexRoute
  '/our-team/': typeof OurTeamIndexRoute
  '/video-archive/': typeof VideoArchiveIndexRoute
  '/immigration-services/$category/$slug': typeof ImmigrationServicesCategorySlugRoute
  '/immigration-services/$category/': typeof ImmigrationServicesCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/immigration-links': typeof ImmigrationLinksRoute
  '/testimonials': typeof TestimonialsRoute
  '/about-us/community-involvement': typeof AboutUsCommunityInvolvementRoute
  '/about-us/why-akula': typeof AboutUsWhyAkulaRoute
  '/news-blogs/$slug': typeof NewsBlogsSlugRoute
  '/our-team/$slug': typeof OurTeamSlugRoute
  '/our-team/full-team': typeof OurTeamFullTeamRoute
  '/video-archive/firm-videos': typeof VideoArchiveFirmVideosRoute
  '/about-us': typeof AboutUsIndexRoute
  '/immigration-services': typeof ImmigrationServicesIndexRoute
  '/news-blogs': typeof NewsBlogsIndexRoute
  '/our-team': typeof OurTeamIndexRoute
  '/video-archive': typeof VideoArchiveIndexRoute
  '/immigration-services/$category/$slug': typeof ImmigrationServicesCategorySlugRoute
  '/immigration-services/$category': typeof ImmigrationServicesCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/immigration-links': typeof ImmigrationLinksRoute
  '/testimonials': typeof TestimonialsRoute
  '/about-us/community-involvement': typeof AboutUsCommunityInvolvementRoute
  '/about-us/why-akula': typeof AboutUsWhyAkulaRoute
  '/news-blogs/$slug': typeof NewsBlogsSlugRoute
  '/our-team/$slug': typeof OurTeamSlugRoute
  '/our-team/full-team': typeof OurTeamFullTeamRoute
  '/video-archive/firm-videos': typeof VideoArchiveFirmVideosRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/immigration-services/': typeof ImmigrationServicesIndexRoute
  '/news-blogs/': typeof NewsBlogsIndexRoute
  '/our-team/': typeof OurTeamIndexRoute
  '/video-archive/': typeof VideoArchiveIndexRoute
  '/immigration-services/$category/$slug': typeof ImmigrationServicesCategorySlugRoute
  '/immigration-services/$category/': typeof ImmigrationServicesCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/immigration-links'
    | '/testimonials'
    | '/about-us/community-involvement'
    | '/about-us/why-akula'
    | '/news-blogs/$slug'
    | '/our-team/$slug'
    | '/our-team/full-team'
    | '/video-archive/firm-videos'
    | '/about-us/'
    | '/immigration-services/'
    | '/news-blogs/'
    | '/our-team/'
    | '/video-archive/'
    | '/immigration-services/$category/$slug'
    | '/immigration-services/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/immigration-links'
    | '/testimonials'
    | '/about-us/community-involvement'
    | '/about-us/why-akula'
    | '/news-blogs/$slug'
    | '/our-team/$slug'
    | '/our-team/full-team'
    | '/video-archive/firm-videos'
    | '/about-us'
    | '/immigration-services'
    | '/news-blogs'
    | '/our-team'
    | '/video-archive'
    | '/immigration-services/$category/$slug'
    | '/immigration-services/$category'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/immigration-links'
    | '/testimonials'
    | '/about-us/community-involvement'
    | '/about-us/why-akula'
    | '/news-blogs/$slug'
    | '/our-team/$slug'
    | '/our-team/full-team'
    | '/video-archive/firm-videos'
    | '/about-us/'
    | '/immigration-services/'
    | '/news-blogs/'
    | '/our-team/'
    | '/video-archive/'
    | '/immigration-services/$category/$slug'
    | '/immigration-services/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ImmigrationLinksRoute: typeof ImmigrationLinksRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AboutUsCommunityInvolvementRoute: typeof AboutUsCommunityInvolvementRoute
  AboutUsWhyAkulaRoute: typeof AboutUsWhyAkulaRoute
  NewsBlogsSlugRoute: typeof NewsBlogsSlugRoute
  OurTeamSlugRoute: typeof OurTeamSlugRoute
  OurTeamFullTeamRoute: typeof OurTeamFullTeamRoute
  VideoArchiveFirmVideosRoute: typeof VideoArchiveFirmVideosRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  ImmigrationServicesIndexRoute: typeof ImmigrationServicesIndexRoute
  NewsBlogsIndexRoute: typeof NewsBlogsIndexRoute
  OurTeamIndexRoute: typeof OurTeamIndexRoute
  VideoArchiveIndexRoute: typeof VideoArchiveIndexRoute
  ImmigrationServicesCategorySlugRoute: typeof ImmigrationServicesCategorySlugRoute
  ImmigrationServicesCategoryIndexRoute: typeof ImmigrationServicesCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration-links': {
      id: '/immigration-links'
      path: '/immigration-links'
      fullPath: '/immigration-links'
      preLoaderRoute: typeof ImmigrationLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/community-involvement': {
      id: '/about-us/community-involvement'
      path: '/about-us/community-involvement'
      fullPath: '/about-us/community-involvement'
      preLoaderRoute: typeof AboutUsCommunityInvolvementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/why-akula': {
      id: '/about-us/why-akula'
      path: '/about-us/why-akula'
      fullPath: '/about-us/why-akula'
      preLoaderRoute: typeof AboutUsWhyAkulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration-services/': {
      id: '/immigration-services/'
      path: '/immigration-services'
      fullPath: '/immigration-services/'
      preLoaderRoute: typeof ImmigrationServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-blogs/': {
      id: '/news-blogs/'
      path: '/news-blogs'
      fullPath: '/news-blogs/'
      preLoaderRoute: typeof NewsBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-blogs/$slug': {
      id: '/news-blogs/$slug'
      path: '/news-blogs/$slug'
      fullPath: '/news-blogs/$slug'
      preLoaderRoute: typeof NewsBlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team/': {
      id: '/our-team/'
      path: '/our-team'
      fullPath: '/our-team/'
      preLoaderRoute: typeof OurTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team/$slug': {
      id: '/our-team/$slug'
      path: '/our-team/$slug'
      fullPath: '/our-team/$slug'
      preLoaderRoute: typeof OurTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team/full-team': {
      id: '/our-team/full-team'
      path: '/our-team/full-team'
      fullPath: '/our-team/full-team'
      preLoaderRoute: typeof OurTeamFullTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-archive/': {
      id: '/video-archive/'
      path: '/video-archive'
      fullPath: '/video-archive/'
      preLoaderRoute: typeof VideoArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-archive/firm-videos': {
      id: '/video-archive/firm-videos'
      path: '/video-archive/firm-videos'
      fullPath: '/video-archive/firm-videos'
      preLoaderRoute: typeof VideoArchiveFirmVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration-services/$category/': {
      id: '/immigration-services/$category/'
      path: '/immigration-services/$category'
      fullPath: '/immigration-services/$category/'
      preLoaderRoute: typeof ImmigrationServicesCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration-services/$category/$slug': {
      id: '/immigration-services/$category/$slug'
      path: '/immigration-services/$category/$slug'
      fullPath: '/immigration-services/$category/$slug'
      preLoaderRoute: typeof ImmigrationServicesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ImmigrationLinksRoute: ImmigrationLinksRoute,
  TestimonialsRoute: TestimonialsRoute,
  AboutUsCommunityInvolvementRoute: AboutUsCommunityInvolvementRoute,
  AboutUsWhyAkulaRoute: AboutUsWhyAkulaRoute,
  NewsBlogsSlugRoute: NewsBlogsSlugRoute,
  OurTeamSlugRoute: OurTeamSlugRoute,
  OurTeamFullTeamRoute: OurTeamFullTeamRoute,
  VideoArchiveFirmVideosRoute: VideoArchiveFirmVideosRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  ImmigrationServicesIndexRoute: ImmigrationServicesIndexRoute,
  NewsBlogsIndexRoute: NewsBlogsIndexRoute,
  OurTeamIndexRoute: OurTeamIndexRoute,
  VideoArchiveIndexRoute: VideoArchiveIndexRoute,
  ImmigrationServicesCategorySlugRoute: ImmigrationServicesCategorySlugRoute,
  ImmigrationServicesCategoryIndexRoute: ImmigrationServicesCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

